version: '2'
services:
  big-structure:
    build:
      context: ./big-structure/
    environment:
      - GUNICORN_WORKERS=2
      - APP_PORT=8181
    depends_on:
      - mongo
      - redis
    ports:
      - "8181:8181"
    restart: always
    volumes:
      - ./big-structure:/app
  mongo:
    image: mongo
  redis:
    image: redis
