version: '2'
services:
  big-structure:
    build:
      context: ./big-structure/
    environment:
      - GUNICORN_WORKERS=2
      - APP_PORT=8181
    depends_on:
      - redis
    ports:
      - "8181:8181"
    restart: always
    volumes:
      - ./big-structure:/app
      - ./dependencies_for_de-stress:/dependencies_for_de-stress
  rq-worker:
    build:
      context: ./big-structure/
    depends_on:
      - big-structure
      - redis
    restart: always
    volumes:
      - ./big-structure:/app
      - ./dependencies_for_de-stress:/dependencies_for_de-stress
    command: rq worker --url redis://redis:6379 --disable-job-desc-logging
  redis:
    image: redis
