version: '2'
services:
  big-structure:
    build:
      context: ./big-structure/
    environment:
      - POSTGRES_PASSWORD
      - EVOEF2_BINARY_PATH
      - DFIRE2_FOLDER_PATH
      - ROSETTA_BINARY_PATH
      - AGGRESCAN3D_SCRIPT_PATH
      - GUNICORN_WORKERS
      - APP_PORT
      - MAX_RUN_TIME
    depends_on:
      - redis
    ports:
      - "${APP_PORT}:${APP_PORT}"
    restart: always
    volumes:
      - ./big-structure:/app
      - ./dependencies_for_de-stress:/dependencies_for_de-stress
  database:
    build:
      context: ./database/
    environment:
      - POSTGRES_PASSWORD
    restart: always
  rq-worker:
    build:
      context: ./big-structure/
    environment:
      - POSTGRES_PASSWORD
      - EVOEF2_BINARY_PATH
      - DFIRE2_FOLDER_PATH
      - ROSETTA_BINARY_PATH
      - AGGRESCAN3D_SCRIPT_PATH
      - MAX_RUN_TIME
    depends_on:
      - big-structure
      - redis
    restart: always
    volumes:
      - ./big-structure:/app
      - ./dependencies_for_de-stress:/dependencies_for_de-stress
    command: rq worker --url redis://redis:6379 --disable-job-desc-logging
  redis:
    image: redis
  dashboard:
    image: eoranged/rq-dashboard
    environment:
      - RQ_DASHBOARD_REDIS_URL
      - RQ_DASHBOARD_PORT
    depends_on:
      - redis
    ports:
      - "${RQ_DASHBOARD_PORT}:${RQ_DASHBOARD_PORT}"
      
