version: '2'
services:
  destress-front-end:
    build:
      context: ./front-end/
  destress-big-structure:
    build:
      context: ./big-structure/
    environment:
      - GUNICORN_WORKERS=2
    depends_on:
      - redis
    restart: always
  destress-rq-worker:
    build:
      context: ./big-structure/
    depends_on:
      - big-structure
      - redis
    restart: always
    command: rq worker --url redis://redis:6379 --disable-job-desc-logging
  destress-redis:
    image: redis
