name: Big Structure Tests

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/big-structure-run-tests.yml'
      - 'big-structure/**'
  pull_request:
    paths:
      - '.github/workflows/big-structure-run-tests.yml'
      - 'big-structure/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout de-stress
        uses: actions/checkout@v2

      - name: Checkout de-stress_dependencies
        uses: actions/checkout@v2
        with:
          repository: wells-wood-research/de-stress_dependencies.git
          token: ${{ secrets.DEPENDENCIES_ACCESS_TOKEN }}
          ref: master
          path: de-stress_dependencies

      - name: Build and test `big-structure`   
        run: |
          chmod -R 755 de-stress_dependencies/
          cp -r de-stress_dependencies/ big-structure/dependencies_for_isambard/de-stress_dependencies/
          cd big-structure/
          cp .env-testing .env
          docker build -t big-structure .
          docker run --rm big-structure poetry run pytest
          