name: Big Structure Run Tests

on:
  push:
    branches:
      - master
    paths:
      'big-structure/*'
  pull_request:
    paths:
      'big-structure/*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build and test `big-structure`.
      run: |
        cd big-structure/
        docker build -t big-structure-run-tests .
        docker run --rm big-structure-run-tests
