name: Big Structure Tests

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/big-structure-run-tests.yml'
      - 'big-structure/**'
  pull_request:
    paths:
      - '.github/workflows/big-structure-run-tests.yml'
      - 'big-structure/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build and test `big-structure` 
      with:
          repository: wells-wood-research/de-stress_dependencies.git
          token: ${{ secrets.DEPENDENCIES_ACCESS_TOKEN }}
          ref: master
          path: /home/runner/work/de-stress/big-structure/de-stress_dependencies/
      run: |
        chmod -R 755 /home/runner/work/de-stress/big-structure/de-stress_dependencies/
        cd big-structure/
        cp .env-testing .env
        docker build -t big-structure .
        docker run --rm big-structure poetry run pytest
        
        
      

