name: Front End Tests

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/front-end-tests.yml'
      - 'front-end/*'
  pull_request:
    paths:
      - '.github/workflows/front-end-tests.yml'
      - 'front-end/*'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build and test `big-structure`.
        run: |
          cd front-end/
          docker build -t destress-front-end .
          docker run --rm destress-front-end npm test
