name: Front End Tests

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/front-end-tests.yml'
      - 'front-end/*'
  pull_request:
    paths:
      - '.github/workflows/front-end-tests.yml'
      - 'front-end/*'
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        cd front-end/
        npm install
        npm test
