name: Front End Tests

on:
  push:
    branches:
      - master
    paths:
      - 'front-end/*'
  pull_request:
    paths:
      - 'front-end/*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the application.
      run: |
        cd front-end/
        docker build -t front-end-test .
        docker run --rm front-end-test
