name: Front End Test Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the application.
      run: |
        cd front-end/
        docker build -t front-end-build-test .
        docker run --rm front-end-build-test
